version: '3.7'

services:

  worker:
    depends_on:
    - mariadb
    entrypoint: /bin/bash -c '/usr/sbin/update-ca-certificates \
        && dotnet NetworkTest.WorkerService.dll'
    environment:
      DOTNET_ENVIRONMENT: Production
      Database:Database: networktest
      Database:Port: "3306"
      Database:Server: mariadb
      Database:UserId: networktest
      Logging:LogLevel:Default: Debug
      Ping:Timeout: "2000"
      Test:HostNameOrIPAddress: lau.packetlosstest.com
      Test:MillisecondInterval: "1800000"
      Test:MillisecondDuration: "20000"
    image: eassbhhtgu/networktest:latest
    secrets:
    - source: Database_Password
    - source: ca.crt
      target: /usr/local/share/ca-certificates/ca.crt

  mariadb:
    command: /bin/sh -c "openssl x509 -in /usr/certs/ca.crt -out /usr/certs/ca.pem -outform PEM \
        && openssl x509 -in /usr/certs/server.crt -out /usr/certs/server.pem -outform PEM \
        && openssl rsa -in /usr/certs/server.key -text > /usr/certs/server_key.pem \
        && docker-entrypoint.sh mariadbd \
            --require_secure_transport=ON \
            --ssl-ca=/usr/certs/ca.pem \
            --ssl-cert=/usr/certs/server.pem \
            --ssl-key=/usr/certs/server_key.pem"
    environment:
      MARIADB_DATABASE: networktest
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: networktest
      MARIADB_PASSWORD_FILE: /run/secrets/Database_Password
    image: eassbhhtgu/networktest-db:latest
    ports:
    - 3306:3306/tcp
    secrets:
    - source: Database_Password
    - source: ca.crt
      target: /usr/certs/ca.crt
    - source: server.crt
      target: /usr/certs/server.crt
    - source: server.key
      target: /usr/certs/server.key
    volumes:
    - mariadb-volume:/var/lib/mysql:rw

secrets:
  Database_Password:
    external: true
    name: networktest_mariadb_password
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  server.crt:
    file: ${USERPROFILE}\.aspnet\https\mariadb.crt
  server.key:
    file: ${USERPROFILE}\.aspnet\https\mariadb.key

volumes:
  mariadb-volume: {}
