version: '3.7'

services:
  mariadb:
    image: eassbhhtgu/networktest-db:latest
    command: /bin/sh -c "mkdir /usr/certs/ \
        && openssl x509 -in /run/secrets/ca.crt -out /usr/certs/ca.pem -outform PEM \
        && openssl x509 -in /run/secrets/localhost.crt -out /usr/certs/server.pem -outform PEM \
        && openssl rsa -in /run/secrets/localhost.key -text > /usr/certs/server_key.pem \
        && docker-entrypoint.sh mariadbd \
            --require_secure_transport=ON \
            --ssl-ca=/usr/certs/ca.pem \
            --ssl-cert=/usr/certs/server.pem \
            --ssl-key=/usr/certs/server_key.pem"
    environment:
      MARIADB_DATABASE: networktest
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MARIADB_USER: networktest
      MARIADB_PASSWORD: networktest
    ports:
    - 3306:3306/tcp
    secrets:
    - source: ca.crt
    - source: localhost.crt
    - source: localhost.key
    volumes:
    - mariadb-volume:/var/lib/mysql:rw

secrets:
  ca.crt:
    file: ${USERPROFILE}\.aspnet\https\ca.crt
  localhost.crt:
    file: ${USERPROFILE}\.aspnet\https\localhost.crt
  localhost.key:
    file: ${USERPROFILE}\.aspnet\https\localhost.key
    
volumes:
  mariadb-volume: {}
